"""v0.2.0 jobs, sessions, settings, knowledge bases, series, schedules

Revision ID: a84d02706068
Revises: d9c35cb3ad54
Create Date: 2026-10-05 00:37:29.399596
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a84d02706068'
down_revision: Union[str, None] = 'd9c35cb3ad54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("ALTER TYPE job_type ADD VALUE IF NOT EXISTS 'AI_REWRITE'")
        op.execute("ALTER TYPE job_type ADD VALUE IF NOT EXISTS 'TELEGRAM_RETRY'")
        for enum_name in ("ai_operation", "ai_operation_cost_event"):
            for value in ("IMPROVE", "GENERATE_CTA", "REMOVE_CLICHES"):
                op.execute(f"ALTER TYPE {enum_name} ADD VALUE IF NOT EXISTS '{value}'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_workspace_id'), 'knowledge_bases', ['workspace_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('workspace_settings',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('default_tone_profile_id', sa.Uuid(), nullable=True),
    sa.Column('cta_defaults_json', sa.Text(), nullable=False),
    sa.Column('misfire_policy', sa.String(length=30), nullable=False),
    sa.Column('misfire_grace_minutes', sa.Integer(), nullable=False),
    sa.Column('notification_prefs_json', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_tone_profile_id'], ['tone_of_voice_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.add_column('autopilot_configs', sa.Column('budget_warning_pct', sa.Integer(), nullable=False, server_default=sa.text("'80'")))
    op.add_column('content_items', sa.Column('series_id', sa.Uuid(), nullable=True))
    op.add_column('content_items', sa.Column('source_item_id', sa.Uuid(), nullable=True))
    op.add_column('content_items', sa.Column('schedule_id', sa.Uuid(), nullable=True))
    op.add_column('content_items', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_content_items_series_id'), 'content_items', ['series_id'], unique=False)
    op.create_foreign_key('fk_content_items_series_id_content_series', 'content_items', 'content_series', ['series_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_content_items_source_item_id_source_items', 'content_items', 'source_items', ['source_item_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_content_items_schedule_id_schedules', 'content_items', 'schedules', ['schedule_id'], ['id'], ondelete='SET NULL')
    op.add_column('content_series', sa.Column('category', sa.String(length=100), nullable=False, server_default=sa.text("''")))
    op.add_column('content_series', sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'ACTIVE'")))
    op.add_column('content_series', sa.Column('numbering_format', sa.String(length=40), nullable=False, server_default=sa.text("'#{n:03d}'")))
    op.add_column('content_series', sa.Column('schedule_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_content_series_schedule_id_schedules', 'content_series', 'schedules', ['schedule_id'], ['id'], ondelete='SET NULL')
    op.add_column('jobs', sa.Column('created_by_user_id', sa.Uuid(), nullable=True))
    op.add_column('jobs', sa.Column('entity_type', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('entity_id', sa.String(length=64), nullable=True))
    op.add_column('jobs', sa.Column('payload_summary', sa.String(length=500), nullable=False, server_default=sa.text("''")))
    op.add_column('jobs', sa.Column('progress', sa.Integer(), nullable=False, server_default=sa.text("'0'")))
    op.add_column('jobs', sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('worker', sa.String(length=200), nullable=True))
    op.add_column('jobs', sa.Column('error_code', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('metadata_json', sa.Text(), nullable=False, server_default=sa.text("'{}'")))
    op.create_index(op.f('ix_jobs_entity_id'), 'jobs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_jobs_entity_type'), 'jobs', ['entity_type'], unique=False)
    op.create_foreign_key('fk_jobs_created_by_user_id_users', 'jobs', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.execute("UPDATE jobs SET error_message = error WHERE error IS NOT NULL")
    op.execute("UPDATE jobs SET queued_at = created_at WHERE queued_at IS NULL")
    op.drop_column('jobs', 'error')
    op.add_column('knowledge_chunks', sa.Column('kind', sa.String(length=40), nullable=False, server_default=sa.text("'FACT'")))
    op.add_column('knowledge_chunks', sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('metadata_json', sa.Text(), nullable=False, server_default=sa.text("'{}'")))
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.add_column('knowledge_documents', sa.Column('knowledge_base_id', sa.Uuid(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('kind', sa.String(length=40), nullable=False, server_default=sa.text("'FACT'")))
    op.add_column('knowledge_documents', sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('knowledge_documents', sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('knowledge_documents', sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('knowledge_documents', sa.Column('parse_warnings_json', sa.Text(), nullable=False, server_default=sa.text("'[]'")))
    op.create_index(op.f('ix_knowledge_documents_kind'), 'knowledge_documents', ['kind'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_knowledge_base_id'), 'knowledge_documents', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_workspace_id'), 'knowledge_documents', ['workspace_id'], unique=False)
    op.create_foreign_key('fk_knowledge_documents_knowledge_base_id_knowledge_bases', 'knowledge_documents', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='CASCADE')
    op.add_column('schedules', sa.Column('categories_json', sa.Text(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('schedules', sa.Column('misfire_policy', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'misfire_policy')
    op.drop_column('schedules', 'categories_json')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_knowledge_documents_knowledge_base_id_knowledge_bases', 'knowledge_documents', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_documents_workspace_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_knowledge_base_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_kind'), table_name='knowledge_documents')
    op.drop_column('knowledge_documents', 'parse_warnings_json')
    op.drop_column('knowledge_documents', 'valid_until')
    op.drop_column('knowledge_documents', 'valid_from')
    op.drop_column('knowledge_documents', 'enabled')
    op.drop_column('knowledge_documents', 'kind')
    op.drop_column('knowledge_documents', 'knowledge_base_id')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_column('knowledge_chunks', 'metadata_json')
    op.drop_column('knowledge_chunks', 'effective_at')
    op.drop_column('knowledge_chunks', 'kind')
    op.add_column('jobs', sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True))
    op.execute("UPDATE jobs SET error = error_message")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_jobs_created_by_user_id_users', 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_entity_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_entity_id'), table_name='jobs')
    op.drop_column('jobs', 'metadata_json')
    op.drop_column('jobs', 'error_message')
    op.drop_column('jobs', 'error_code')
    op.drop_column('jobs', 'worker')
    op.drop_column('jobs', 'next_retry_at')
    op.drop_column('jobs', 'queued_at')
    op.drop_column('jobs', 'progress')
    op.drop_column('jobs', 'payload_summary')
    op.drop_column('jobs', 'entity_id')
    op.drop_column('jobs', 'entity_type')
    op.drop_column('jobs', 'created_by_user_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_content_series_schedule_id_schedules', 'content_series', type_='foreignkey')
    op.drop_column('content_series', 'schedule_id')
    op.drop_column('content_series', 'numbering_format')
    op.drop_column('content_series', 'status')
    op.drop_column('content_series', 'category')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_content_items_schedule_id_schedules', 'content_items', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_content_items_source_item_id_source_items', 'content_items', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_content_items_series_id_content_series', 'content_items', type_='foreignkey')
    op.drop_index(op.f('ix_content_items_series_id'), table_name='content_items')
    op.drop_column('content_items', 'deleted_at')
    op.drop_column('content_items', 'schedule_id')
    op.drop_column('content_items', 'source_item_id')
    op.drop_column('content_items', 'series_id')
    op.drop_column('autopilot_configs', 'budget_warning_pct')
    op.drop_table('workspace_settings')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_knowledge_bases_workspace_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
