"""user language preference

Revision ID: bee55cb8fd0b
Revises: a84d02706068
Create Date: 2026-10-05 02:55:44.911129
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bee55cb8fd0b'
down_revision: Union[str, None] = 'a84d02706068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    # ### end Alembic commands ###
