"""init

Revision ID: d9c35cb3ad54
Revises: 
Create Date: 2026-10-04 23:24:24.038321
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd9c35cb3ad54'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('audit_logs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_sets',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mode', sa.Enum('EXACT', 'CTA_PER_CHANNEL', 'CONTACT_PER_CHANNEL', 'ADAPTED', name='channel_set_mode'), nullable=False),
    sa.Column('autopilot_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.Enum('AI_GENERATE_POST', 'AI_REWRITE_POST', 'AI_GENERATE_IMAGE', 'TELEGRAM_PUBLISH', 'TELEGRAM_REFRESH_CHANNELS', 'TELEGRAM_REFRESH_METRICS', 'SOURCE_FETCH', 'AUTOPILOT_PLAN', name='job_type'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCESS', 'RETRYING', 'FAILED', 'CANCELLED', name='job_status'), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_assets',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('bucket', sa.String(length=200), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'UPLOADED', 'USED', 'UNUSED', 'ARCHIVED', name='media_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tone_of_voice_profiles',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('addressing', sa.String(length=50), nullable=False),
    sa.Column('formality', sa.String(length=50), nullable=False),
    sa.Column('emoji_policy', sa.String(length=50), nullable=False),
    sa.Column('average_length', sa.String(length=50), nullable=False),
    sa.Column('paragraph_style', sa.String(length=100), nullable=False),
    sa.Column('headline_style', sa.String(length=100), nullable=False),
    sa.Column('cta_style', sa.String(length=100), nullable=False),
    sa.Column('allowed_vocabulary_json', sa.Text(), nullable=False),
    sa.Column('forbidden_vocabulary_json', sa.Text(), nullable=False),
    sa.Column('cliches_blacklist_json', sa.Text(), nullable=False),
    sa.Column('good_examples_json', sa.Text(), nullable=False),
    sa.Column('bad_examples_json', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'EDITOR', 'APPROVER', 'VIEWER', name='workspace_role'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_items',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('IDEA', 'DRAFT', 'GENERATING', 'PENDING_APPROVAL', 'APPROVED', 'SCHEDULED', 'PUBLISHING', 'PUBLISHED', 'PARTIALLY_PUBLISHED', 'FAILED', 'REJECTED', 'ARCHIVED', name='content_status'), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('angle', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('plain_text', sa.Text(), nullable=False),
    sa.Column('telegram_html', sa.Text(), nullable=False),
    sa.Column('cta_key', sa.String(length=100), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('sources_json', sa.Text(), nullable=False),
    sa.Column('media_asset_id', sa.Uuid(), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=False),
    sa.Column('duplicate_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('duplicate_score', sa.Double(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('risk_flags_json', sa.Text(), nullable=False),
    sa.Column('tone_profile_id', sa.Uuid(), nullable=True),
    sa.Column('channel_set_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_set_id'], ['channel_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tone_profile_id'], ['tone_of_voice_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_series',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('channel_set_id', sa.Uuid(), nullable=True),
    sa.Column('tone_profile_id', sa.Uuid(), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('sequence_counter', sa.Integer(), nullable=False),
    sa.Column('planned_topics_json', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_set_id'], ['channel_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tone_profile_id'], ['tone_of_voice_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_attempts',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCESS', 'RETRYING', 'FAILED', 'CANCELLED', name='job_attempt_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('source_filename', sa.String(length=300), nullable=False),
    sa.Column('media_asset_id', sa.Uuid(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('channel_set_id', sa.Uuid(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('posts_per_day', sa.Integer(), nullable=False),
    sa.Column('days_of_week_json', sa.Text(), nullable=False),
    sa.Column('min_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('max_posts_per_day', sa.Integer(), nullable=False),
    sa.Column('exclude_dates_json', sa.Text(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('randomize_within_window', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_set_id'], ['channel_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_items',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('url_verified', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('freshness_score', sa.Double(), nullable=False),
    sa.Column('relevance_score', sa.Double(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'SHORTLISTED', 'USED', 'DISMISSED', name='idea_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_accounts',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('phone_encrypted', sa.Text(), nullable=False),
    sa.Column('phone_masked', sa.String(length=32), nullable=False),
    sa.Column('session_encrypted', sa.Text(), nullable=True),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('avatar_media_asset_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'AUTH_REQUIRED', 'TWO_FA_REQUIRED', 'FLOOD_WAIT', 'ERROR', 'DISABLED', name='telegram_account_status'), nullable=False),
    sa.Column('flood_wait_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['avatar_media_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_requests',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_item_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.Enum('GENERATE_POST', 'REWRITE', 'SHORTEN', 'EXPAND', 'CHANGE_TONE', 'REGENERATE_TITLE', 'REGENERATE_FRAGMENT', 'GENERATE_IMAGE_PROMPT', 'GENERATE_IMAGE', name='ai_operation'), nullable=False),
    sa.Column('provider_request_id', sa.String(length=200), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('input_rate_rub_per_m', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('output_rate_rub_per_m', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('input_cost_rub', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('output_cost_rub', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_cost_rub', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'RETRIED', name='ai_request_status'), nullable=False),
    sa.Column('raw_usage_json', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autopilot_configs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('MANUAL', 'APPROVAL', 'AUTOPILOT', name='autopilot_mode'), nullable=False),
    sa.Column('channel_set_id', sa.Uuid(), nullable=True),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.Column('posts_per_day', sa.Integer(), nullable=False),
    sa.Column('category_mix_json', sa.Text(), nullable=False),
    sa.Column('tone_profile_id', sa.Uuid(), nullable=True),
    sa.Column('generate_image', sa.Boolean(), nullable=False),
    sa.Column('max_cost_per_post_rub', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('daily_budget_rub', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('monthly_budget_rub', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('duplicate_block_threshold', sa.Double(), nullable=False),
    sa.Column('duplicate_warning_threshold', sa.Double(), nullable=False),
    sa.Column('require_sources_for_news', sa.Boolean(), nullable=False),
    sa.Column('max_image_regenerations', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_set_id'], ['channel_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tone_profile_id'], ['tone_of_voice_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('distribution_batches',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('channel_set_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHING', 'SUCCESS', 'PARTIAL_FAILURE', 'FAILED', name='batch_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_set_id'], ['channel_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_rules',
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('window_start', sa.String(length=5), nullable=False),
    sa.Column('window_end', sa.String(length=5), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series_items',
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['content_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_channels',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_entity_id', sa.BigInteger(), nullable=False),
    sa.Column('access_hash', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('avatar_media_asset_id', sa.Uuid(), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('can_post', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('autopilot_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_cta_key', sa.String(length=100), nullable=True),
    sa.Column('tone_profile_id', sa.Uuid(), nullable=True),
    sa.Column('knowledge_scope_tags', sa.Text(), nullable=False),
    sa.Column('health', sa.Enum('HEALTHY', 'NO_POST_PERMISSION', 'ACCOUNT_OFFLINE', 'FLOOD_WAIT', 'UNAVAILABLE', name='channel_health'), nullable=False),
    sa.Column('cta_overrides_json', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['avatar_media_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tone_profile_id'], ['tone_of_voice_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_set_members',
    sa.Column('channel_set_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['telegram_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_set_id'], ['channel_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_revisions',
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('edited_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('plain_text', sa.Text(), nullable=False),
    sa.Column('telegram_html', sa.Text(), nullable=False),
    sa.Column('ai_request_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_request_id'], ['ai_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_events',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('ai_request_id', sa.Uuid(), nullable=True),
    sa.Column('content_item_id', sa.Uuid(), nullable=True),
    sa.Column('channel_id', sa.Uuid(), nullable=True),
    sa.Column('channel_set_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.Enum('GENERATE_POST', 'REWRITE', 'SHORTEN', 'EXPAND', 'CHANGE_TONE', 'REGENERATE_TITLE', 'REGENERATE_FRAGMENT', 'GENERATE_IMAGE_PROMPT', 'GENERATE_IMAGE', name='ai_operation_cost_event'), nullable=False),
    sa.Column('amount_rub', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_request_id'], ['ai_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['telegram_channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_set_id'], ['channel_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_generations',
    sa.Column('media_asset_id', sa.Uuid(), nullable=False),
    sa.Column('content_item_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('cost_total_rub', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('ai_request_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_request_id'], ['ai_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_asset_id')
    )
    op.create_table('publications',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLAIMED', 'SENDING', 'SUCCESS', 'FAILED', name='publication_status'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('rendered_text', sa.Text(), nullable=False),
    sa.Column('resolved_cta', sa.String(length=300), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('flood_wait_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['distribution_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['telegram_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('post_metric_snapshots',
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('forwards', sa.Integer(), nullable=False),
    sa.Column('reactions', sa.Integer(), nullable=False),
    sa.Column('replies', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_metric_snapshots')
    op.drop_table('publications')
    op.drop_table('media_generations')
    op.drop_table('cost_events')
    op.drop_table('content_revisions')
    op.drop_table('channel_set_members')
    op.drop_table('telegram_channels')
    op.drop_table('series_items')
    op.drop_table('schedule_rules')
    op.drop_table('knowledge_chunks')
    op.drop_table('distribution_batches')
    op.drop_table('autopilot_configs')
    op.drop_table('ai_requests')
    op.drop_table('telegram_accounts')
    op.drop_table('source_items')
    op.drop_table('schedules')
    op.drop_table('knowledge_documents')
    op.drop_table('job_attempts')
    op.drop_table('content_series')
    op.drop_table('content_items')
    op.drop_table('workspace_members')
    op.drop_table('tone_of_voice_profiles')
    op.drop_table('sources')
    op.drop_table('notifications')
    op.drop_table('media_assets')
    op.drop_table('jobs')
    op.drop_table('channel_sets')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
    # Autogenerate does not drop native PG enum types; without this a
    # downgrade followed by upgrade fails with DuplicateObject.
    sa.Enum(name='ai_operation_cost_event').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='ai_operation').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='ai_request_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='autopilot_mode').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='batch_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='channel_health').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='channel_set_mode').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='content_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='idea_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='job_attempt_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='job_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='job_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='media_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='publication_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='telegram_account_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='workspace_role').drop(op.get_bind(), checkfirst=True)
